//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleID { get; set; }
        public int BookID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateOfSale { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
